import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('http://localhost:3000/', { waitUntil: 'load' });
await page.evaluate(() => { document.querySelectorAll('.reveal').forEach(el => { el.style.transition='none'; el.classList.add('visible'); }); });
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: 'temporary screenshots/hero-crop.png', clip: { x: 0, y: 60, width: 1440, height: 620 } });
await browser.close();
console.log('done');
